spring:
  datasource:
    url: jdbc:postgresql://localhost:5450/prompt-gen-db
    username: prompt-gen
    password: supersecret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-message: always
    include-stacktrace: always
